CREATE FUNCTION [dbo].[fn_GetPinyin] (@words NVARCHAR(2000))
RETURNS VARCHAR(8000)
AS 
BEGIN
    DECLARE @word NCHAR(1)
    DECLARE @pinyin VARCHAR(8000)
    DECLARE @i INT
    DECLARE @words_len INT
    DECLARE @unicode INT
    SET @pinyin = ''
    SET @i = 1
    SET @words = LTRIM(RTRIM(@words))
    SET @words_len = LEN(@words)
    WHILE (@i <= @words_len) --循环取字符
        BEGIN
            SET @word = SUBSTRING(@words,@i,1)
            SET @unicode = UNICODE(@word)
            SET @pinyin = @pinyin + (CASE WHEN UNICODE(@word) BETWEEN 19968 AND 19968 + 20901
                                          THEN (
												SELECT TOP 1 py FROM (
													SELECT 'A' AS py,N'厑' AS word
													UNION ALL SELECT 'Ai',N'靉'
													UNION ALL SELECT 'An',N'黯'
													UNION ALL SELECT 'Ang',N'醠'
													UNION ALL SELECT 'Ao',N'驁'
													UNION ALL SELECT 'Ba',N'欛'
													UNION ALL SELECT 'Bai',N'瓸' --韛兡瓸
													UNION ALL SELECT 'Ban',N'瓣'
													UNION ALL SELECT 'Bang',N'鎊'
													UNION ALL SELECT 'Bao',N'鑤'
													UNION ALL SELECT 'Bei',N'鐾'
													UNION ALL SELECT 'Ben',N'輽'
													UNION ALL SELECT 'Beng',N'鏰'
													UNION ALL SELECT 'Bi',N'鼊'
													UNION ALL SELECT 'Bian',N'變'
													UNION ALL SELECT 'Biao',N'鰾'
													UNION ALL SELECT 'Bie',N'彆'
													UNION ALL SELECT 'Bin',N'鬢'
													UNION ALL SELECT 'Bing',N'靐'
													UNION ALL SELECT 'Bo',N'蔔'
													UNION ALL SELECT 'Bu',N'簿'
													UNION ALL SELECT 'Ca',N'囃'
													UNION ALL SELECT 'Cai',N'乲' --縩乲
													UNION ALL SELECT 'Can',N'爘'
													UNION ALL SELECT 'Cang',N'賶'
													UNION ALL SELECT 'Cao',N'鼜'
													UNION ALL SELECT 'Ce',N'簎'
													UNION ALL SELECT 'Cen',N'笒'
													UNION ALL SELECT 'Ceng',N'乽' --硛硳岾猠乽
													UNION ALL SELECT 'Cha',N'詫'
													UNION ALL SELECT 'Chai',N'囆'
													UNION ALL SELECT 'Chan',N'顫'
													UNION ALL SELECT 'Chang',N'韔'
													UNION ALL SELECT 'Chao',N'觘'
													UNION ALL SELECT 'Che',N'爡'
													UNION ALL SELECT 'Chen',N'讖'
													UNION ALL SELECT 'Cheng',N'秤'
													UNION ALL SELECT 'Chi',N'鷘'
													UNION ALL SELECT 'Chong',N'銃'
													UNION ALL SELECT 'Chou',N'殠'
													UNION ALL SELECT 'Chu',N'矗'
													UNION ALL SELECT 'Chuai',N'踹'
													UNION ALL SELECT 'Chuan',N'鶨'
													UNION ALL SELECT 'Chuang',N'愴'
													UNION ALL SELECT 'Chui',N'顀'
													UNION ALL SELECT 'Chun',N'蠢'
													UNION ALL SELECT 'Chuo',N'縒'
													UNION ALL SELECT 'Ci',N'嗭' --賜嗭
													UNION ALL SELECT 'Cong',N'謥'
													UNION ALL SELECT 'Cou',N'輳'
													UNION ALL SELECT 'Cu',N'顣'
													UNION ALL SELECT 'Cuan',N'爨'
													UNION ALL SELECT 'Cui',N'臎'
													UNION ALL SELECT 'Cun',N'籿'
													UNION ALL SELECT 'Cuo',N'錯'
													UNION ALL SELECT 'Da',N'橽'
													UNION ALL SELECT 'Dai',N'靆'
													UNION ALL SELECT 'Dan',N'饏'
													UNION ALL SELECT 'Dang',N'闣'
													UNION ALL SELECT 'Dao',N'纛'
													UNION ALL SELECT 'De',N'的'
													UNION ALL SELECT 'Den',N'扽'
													UNION ALL SELECT 'Deng',N'鐙'
													UNION ALL SELECT 'Di',N'螮'
													UNION ALL SELECT 'Dia',N'嗲'
													UNION ALL SELECT 'Dian',N'驔'
													UNION ALL SELECT 'Diao',N'鑃'
													UNION ALL SELECT 'Die',N'嚸' --眰嚸
													UNION ALL SELECT 'Ding',N'顁'
													UNION ALL SELECT 'Diu',N'銩'
													UNION ALL SELECT 'Dong',N'霘'
													UNION ALL SELECT 'Dou',N'鬭'
													UNION ALL SELECT 'Du',N'蠹'
													UNION ALL SELECT 'Duan',N'叾' --籪叾
													UNION ALL SELECT 'Dui',N'譵'
													UNION ALL SELECT 'Dun',N'踲'
													UNION ALL SELECT 'Duo',N'鵽'
													UNION ALL SELECT 'E',N'鱷'
													UNION ALL SELECT 'En',N'摁'
													UNION ALL SELECT 'Eng',N'鞥'
													UNION ALL SELECT 'Er',N'樲'
													UNION ALL SELECT 'Fa',N'髮'
													UNION ALL SELECT 'Fan',N'瀪'
													UNION ALL SELECT 'Fang',N'放'
													UNION ALL SELECT 'Fei',N'靅'
													UNION ALL SELECT 'Fen',N'鱝'
													UNION ALL SELECT 'Feng',N'覅'
													UNION ALL SELECT 'Fo',N'梻'
													UNION ALL SELECT 'Fou',N'鴀'
													UNION ALL SELECT 'Fu',N'猤' --鰒猤
													UNION ALL SELECT 'Ga',N'魀'
													UNION ALL SELECT 'Gai',N'瓂'
													UNION ALL SELECT 'Gan',N'灨'
													UNION ALL SELECT 'Gang',N'戇'
													UNION ALL SELECT 'Gao',N'鋯'
													UNION ALL SELECT 'Ge',N'獦'
													UNION ALL SELECT 'Gei',N'給'
													UNION ALL SELECT 'Gen',N'搄'
													UNION ALL SELECT 'Geng',N'堩' --亙堩啹喼嗰
													UNION ALL SELECT 'Gong',N'兣' --熕贑兝兣
													UNION ALL SELECT 'Gou',N'購'
													UNION ALL SELECT 'Gu',N'顧'
													UNION ALL SELECT 'Gua',N'詿'
													UNION ALL SELECT 'Guai',N'恠'
													UNION ALL SELECT 'Guan',N'鱹'
													UNION ALL SELECT 'Guang',N'撗'
													UNION ALL SELECT 'Gui',N'鱥'
													UNION ALL SELECT 'Gun',N'謴'
													UNION ALL SELECT 'Guo',N'腂'
													UNION ALL SELECT 'Ha',N'哈'
													UNION ALL SELECT 'Hai',N'饚'
													UNION ALL SELECT 'Han',N'鶾'
													UNION ALL SELECT 'Hang',N'沆'
													UNION ALL SELECT 'Hao',N'兞'
													UNION ALL SELECT 'He',N'靏'
													UNION ALL SELECT 'Hei',N'嬒'
													UNION ALL SELECT 'Hen',N'恨'
													UNION ALL SELECT 'Heng',N'堼' --堼囍
													UNION ALL SELECT 'Hong',N'鬨'
													UNION ALL SELECT 'Hou',N'鱟'
													UNION ALL SELECT 'Hu',N'鸌'
													UNION ALL SELECT 'Hua',N'蘳'
													UNION ALL SELECT 'Huai',N'蘾'
													UNION ALL SELECT 'Huan',N'鰀'
													UNION ALL SELECT 'Huang',N'鎤'
													UNION ALL SELECT 'Hui',N'顪'
													UNION ALL SELECT 'Hun',N'諢'
													UNION ALL SELECT 'Huo',N'夻'
													UNION ALL SELECT 'Ji',N'驥'
													UNION ALL SELECT 'Jia',N'嗧'
													UNION ALL SELECT 'Jian',N'鑳'
													UNION ALL SELECT 'Jiang',N'謽'
													UNION ALL SELECT 'Jiao',N'釂'
													UNION ALL SELECT 'Jie',N'繲'
													UNION ALL SELECT 'Jin',N'齽'
													UNION ALL SELECT 'Jing',N'竸'
													UNION ALL SELECT 'Jiong',N'蘔'
													UNION ALL SELECT 'Jiu',N'欍'
													UNION ALL SELECT 'Ju',N'爠'
													UNION ALL SELECT 'Juan',N'羂'
													UNION ALL SELECT 'Jue',N'钁'
													UNION ALL SELECT 'Jun',N'攈'
													UNION ALL SELECT 'Ka',N'鉲'
													UNION ALL SELECT 'Kai',N'乫' --鎎乫
													UNION ALL SELECT 'Kan',N'矙'
													UNION ALL SELECT 'Kang',N'閌'
													UNION ALL SELECT 'Kao',N'鯌'
													UNION ALL SELECT 'Ke',N'騍'
													UNION ALL SELECT 'Ken',N'褃'
													UNION ALL SELECT 'Keng',N'鏗' --巪乬唟厼怾
													UNION ALL SELECT 'Kong',N'廤'
													UNION ALL SELECT 'Kou',N'鷇'
													UNION ALL SELECT 'Ku',N'嚳'
													UNION ALL SELECT 'Kua',N'骻'
													UNION ALL SELECT 'Kuai',N'鱠'
													UNION ALL SELECT 'Kuan',N'窾'
													UNION ALL SELECT 'Kuang',N'鑛'
													UNION ALL SELECT 'Kui',N'鑎'
													UNION ALL SELECT 'Kun',N'睏'
													UNION ALL SELECT 'Kuo',N'穒'
													UNION ALL SELECT 'La',N'鞡'
													UNION ALL SELECT 'Lai',N'籟'
													UNION ALL SELECT 'Lan',N'糷'
													UNION ALL SELECT 'Lang',N'唥'
													UNION ALL SELECT 'Lao',N'軂'
													UNION ALL SELECT 'Le',N'餎'
													UNION ALL SELECT 'Lei',N'脷' --嘞脷
													UNION ALL SELECT 'Leng',N'睖'
													UNION ALL SELECT 'Li',N'瓈'
													UNION ALL SELECT 'Lia',N'倆'
													UNION ALL SELECT 'Lian',N'纞'
													UNION ALL SELECT 'Liang',N'鍄'
													UNION ALL SELECT 'Liao',N'瞭'
													UNION ALL SELECT 'Lie',N'鱲'
													UNION ALL SELECT 'Lin',N'轥' --轥拎
													UNION ALL SELECT 'Ling',N'炩'
													UNION ALL SELECT 'Liu',N'咯' --瓼甅囖咯
													UNION ALL SELECT 'Long',N'贚'
													UNION ALL SELECT 'Lou',N'鏤'
													UNION ALL SELECT 'Lu',N'氇'
													UNION ALL SELECT 'Lv',N'鑢'
													UNION ALL SELECT 'Luan',N'亂'
													UNION ALL SELECT 'Lue',N'擽'
													UNION ALL SELECT 'Lun',N'論'
													UNION ALL SELECT 'Luo',N'鱳'
													UNION ALL SELECT 'Ma',N'嘛'
													UNION ALL SELECT 'Mai',N'霢'
													UNION ALL SELECT 'Man',N'蘰'
													UNION ALL SELECT 'Mang',N'蠎'
													UNION ALL SELECT 'Mao',N'唜'
													UNION ALL SELECT 'Me',N'癦' --癦呅
													UNION ALL SELECT 'Mei',N'嚜'
													UNION ALL SELECT 'Men',N'們'
													UNION ALL SELECT 'Meng',N'霥' --霿踎
													UNION ALL SELECT 'Mi',N'羃'
													UNION ALL SELECT 'Mian',N'麵'
													UNION ALL SELECT 'Miao',N'廟'
													UNION ALL SELECT 'Mie',N'鱴' --鱴瓱
													UNION ALL SELECT 'Min',N'鰵'
													UNION ALL SELECT 'Ming',N'詺'
													UNION ALL SELECT 'Miu',N'謬'
													UNION ALL SELECT 'Mo',N'耱' --耱乮
													UNION ALL SELECT 'Mou',N'麰' --麰蟱
													UNION ALL SELECT 'Mu',N'旀'
													UNION ALL SELECT 'Na',N'魶'
													UNION ALL SELECT 'Nai',N'錼'
													UNION ALL SELECT 'Nan',N'婻'
													UNION ALL SELECT 'Nang',N'齉'
													UNION ALL SELECT 'Nao',N'臑'
													UNION ALL SELECT 'Ne',N'呢'
													UNION ALL SELECT 'Nei',N'焾' --嫩焾
													UNION ALL SELECT 'Nen',N'嫩'
													UNION ALL SELECT 'Neng',N'能' --莻嗯鈪銰啱
													UNION ALL SELECT 'Ni',N'嬺'
													UNION ALL SELECT 'Nian',N'艌'
													UNION ALL SELECT 'Niang',N'釀'
													UNION ALL SELECT 'Niao',N'脲'
													UNION ALL SELECT 'Nie',N'钀'
													UNION ALL SELECT 'Nin',N'拰'
													UNION ALL SELECT 'Ning',N'濘'
													UNION ALL SELECT 'Niu',N'靵'
													UNION ALL SELECT 'Nong',N'齈'
													UNION ALL SELECT 'Nou',N'譳'
													UNION ALL SELECT 'Nu',N'搙'
													UNION ALL SELECT 'Nv',N'衄'
													UNION ALL SELECT 'Nue',N'瘧'
													UNION ALL SELECT 'Nuan',N'燶' --硸黁燶郍
													UNION ALL SELECT 'Nuo',N'桛'
													UNION ALL SELECT 'O',N'鞰' --毮夞乯鞰
													UNION ALL SELECT 'Ou',N'漚'
													UNION ALL SELECT 'Pa',N'袙'
													UNION ALL SELECT 'Pai',N'磗' --鎃磗
													UNION ALL SELECT 'Pan',N'鑻'
													UNION ALL SELECT 'Pang',N'胖'
													UNION ALL SELECT 'Pao',N'礮'
													UNION ALL SELECT 'Pei',N'轡'
													UNION ALL SELECT 'Pen',N'喯'
													UNION ALL SELECT 'Peng',N'喸' --浌巼闏乶喸
													UNION ALL SELECT 'Pi',N'鸊'
													UNION ALL SELECT 'Pian',N'騙'
													UNION ALL SELECT 'Piao',N'慓'
													UNION ALL SELECT 'Pie',N'嫳'
													UNION ALL SELECT 'Pin',N'聘'
													UNION ALL SELECT 'Ping',N'蘋'
													UNION ALL SELECT 'Po',N'魄'
													UNION ALL SELECT 'Pou',N'哛' --兺哛
													UNION ALL SELECT 'Pu',N'曝'
													UNION ALL SELECT 'Qi',N'蟿'
													UNION ALL SELECT 'Qia',N'髂'
													UNION ALL SELECT 'Qian',N'縴'
													UNION ALL SELECT 'Qiang',N'瓩' --羻兛瓩
													UNION ALL SELECT 'Qiao',N'躈'
													UNION ALL SELECT 'Qie',N'籡'
													UNION ALL SELECT 'Qin',N'藽'
													UNION ALL SELECT 'Qing',N'櫦'
													UNION ALL SELECT 'Qiong',N'瓗'
													UNION ALL SELECT 'Qiu',N'糗'
													UNION ALL SELECT 'Qu',N'覻'
													UNION ALL SELECT 'Quan',N'勸'
													UNION ALL SELECT 'Que',N'礭'
													UNION ALL SELECT 'Qun',N'囕'
													UNION ALL SELECT 'Ran',N'橪'
													UNION ALL SELECT 'Rang',N'讓'
													UNION ALL SELECT 'Rao',N'繞'
													UNION ALL SELECT 'Re',N'熱'
													UNION ALL SELECT 'Ren',N'餁'
													UNION ALL SELECT 'Reng',N'陾'
													UNION ALL SELECT 'Ri',N'馹'
													UNION ALL SELECT 'Rong',N'穃'
													UNION ALL SELECT 'Rou',N'嶿'
													UNION ALL SELECT 'Ru',N'擩'
													UNION ALL SELECT 'Ruan',N'礝'
													UNION ALL SELECT 'Rui',N'壡'
													UNION ALL SELECT 'Run',N'橍' --橍挼
													UNION ALL SELECT 'Ruo',N'鶸'
													UNION ALL SELECT 'Sa',N'栍' --櫒栍
													UNION ALL SELECT 'Sai',N'虄' --簺虄
													UNION ALL SELECT 'San',N'閐'
													UNION ALL SELECT 'Sang',N'喪'
													UNION ALL SELECT 'Sao',N'髞'
													UNION ALL SELECT 'Se',N'飋' --裇聓
													UNION ALL SELECT 'Sen',N'篸'
													UNION ALL SELECT 'Seng',N'縇' --閪縇
													UNION ALL SELECT 'Sha',N'霎'
													UNION ALL SELECT 'Shai',N'曬'
													UNION ALL SELECT 'Shan',N'鱔'
													UNION ALL SELECT 'Shang',N'緔'
													UNION ALL SELECT 'Shao',N'潲'
													UNION ALL SELECT 'She',N'欇'
													UNION ALL SELECT 'Shen',N'瘮'
													UNION ALL SELECT 'Sheng',N'賸'
													UNION ALL SELECT 'Shi',N'瓧' --鰘齛兙瓧
													UNION ALL SELECT 'Shou',N'鏉'
													UNION ALL SELECT 'Shu',N'虪'
													UNION ALL SELECT 'Shua',N'誜'
													UNION ALL SELECT 'Shuai',N'卛'
													UNION ALL SELECT 'Shuan',N'腨'
													UNION ALL SELECT 'Shuang',N'灀'
													UNION ALL SELECT 'Shui',N'睡'
													UNION ALL SELECT 'Shun',N'鬊'
													UNION ALL SELECT 'Shuo',N'鑠'
													UNION ALL SELECT 'Si',N'乺' --瀃螦乺
													UNION ALL SELECT 'Song',N'鎹'
													UNION ALL SELECT 'Sou',N'瘶'
													UNION ALL SELECT 'Su',N'鷫'
													UNION ALL SELECT 'Suan',N'算'
													UNION ALL SELECT 'Sui',N'鐩'
													UNION ALL SELECT 'Sun',N'潠'
													UNION ALL SELECT 'Suo',N'蜶'
													UNION ALL SELECT 'Ta',N'襨' --躢襨
													UNION ALL SELECT 'Tai',N'燤'
													UNION ALL SELECT 'Tan',N'賧'
													UNION ALL SELECT 'Tang',N'燙'
													UNION ALL SELECT 'Tao',N'畓' --討畓
													UNION ALL SELECT 'Te',N'蟘'
													UNION ALL SELECT 'Teng',N'朰' --霯唞朰
													UNION ALL SELECT 'Ti',N'趯'
													UNION ALL SELECT 'Tian',N'舚'
													UNION ALL SELECT 'Tiao',N'糶'
													UNION ALL SELECT 'Tie',N'餮'
													UNION ALL SELECT 'Ting',N'乭' --濎乭
													UNION ALL SELECT 'Tong',N'憅'
													UNION ALL SELECT 'Tou',N'透'
													UNION ALL SELECT 'Tu',N'鵵'
													UNION ALL SELECT 'Tuan',N'褖'
													UNION ALL SELECT 'Tui',N'駾'
													UNION ALL SELECT 'Tun',N'坉'
													UNION ALL SELECT 'Tuo',N'籜'
													UNION ALL SELECT 'Wa',N'韤'
													UNION ALL SELECT 'Wai',N'顡'
													UNION ALL SELECT 'Wan',N'贎'
													UNION ALL SELECT 'Wang',N'朢'
													UNION ALL SELECT 'Wei',N'躛'
													UNION ALL SELECT 'Wen',N'璺'
													UNION ALL SELECT 'Weng',N'齆'
													UNION ALL SELECT 'Wo',N'齷'
													UNION ALL SELECT 'Wu',N'鶩'
													UNION ALL SELECT 'Xi',N'衋'
													UNION ALL SELECT 'Xia',N'鏬'
													UNION ALL SELECT 'Xian',N'鼸'
													UNION ALL SELECT 'Xiang',N'鱌'
													UNION ALL SELECT 'Xiao',N'斆'
													UNION ALL SELECT 'Xie',N'躞'
													UNION ALL SELECT 'Xin',N'釁'
													UNION ALL SELECT 'Xing',N'臖'
													UNION ALL SELECT 'Xiong',N'敻'
													UNION ALL SELECT 'Xiu',N'齅'
													UNION ALL SELECT 'Xu',N'蓿'
													UNION ALL SELECT 'Xuan',N'贙'
													UNION ALL SELECT 'Xue',N'瀥'
													UNION ALL SELECT 'Xun',N'鑂'
													UNION ALL SELECT 'Ya',N'齾'
													UNION ALL SELECT 'Yan',N'灩'
													UNION ALL SELECT 'Yang',N'樣'
													UNION ALL SELECT 'Yao',N'鑰'
													UNION ALL SELECT 'Ye',N'岃' --鸈膶岃
													UNION ALL SELECT 'Yi',N'齸'
													UNION ALL SELECT 'Yin',N'檼'
													UNION ALL SELECT 'Ying',N'譍'
													UNION ALL SELECT 'Yo',N'喲'
													UNION ALL SELECT 'Yong',N'醟'
													UNION ALL SELECT 'You',N'鼬'
													UNION ALL SELECT 'Yu',N'爩'
													UNION ALL SELECT 'Yuan',N'願'
													UNION ALL SELECT 'Yue',N'鸙'
													UNION ALL SELECT 'Yun',N'韻'
													UNION ALL SELECT 'Za',N'雥'
													UNION ALL SELECT 'Zai',N'縡'
													UNION ALL SELECT 'Zan',N'饡'
													UNION ALL SELECT 'Zang',N'臟'
													UNION ALL SELECT 'Zao',N'竈'
													UNION ALL SELECT 'Ze',N'稄'
													UNION ALL SELECT 'Zei',N'鱡'
													UNION ALL SELECT 'Zen',N'囎'
													UNION ALL SELECT 'Zeng',N'贈'
													UNION ALL SELECT 'Zha',N'醡'
													UNION ALL SELECT 'Zhai',N'瘵'
													UNION ALL SELECT 'Zhan',N'驏'
													UNION ALL SELECT 'Zhang',N'瞕'
													UNION ALL SELECT 'Zhao',N'羄'
													UNION ALL SELECT 'Zhe',N'鷓'
													UNION ALL SELECT 'Zhen',N'黮'
													UNION ALL SELECT 'Zheng',N'證'
													UNION ALL SELECT 'Zhi',N'豒'
													UNION ALL SELECT 'Zhong',N'諥'
													UNION ALL SELECT 'Zhou',N'驟'
													UNION ALL SELECT 'Zhu',N'鑄'
													UNION ALL SELECT 'Zhua',N'爪'
													UNION ALL SELECT 'Zhuai',N'跩'
													UNION ALL SELECT 'Zhuan',N'籑'
													UNION ALL SELECT 'Zhuang',N'戅'
													UNION ALL SELECT 'Zhui',N'鑆'
													UNION ALL SELECT 'Zhun',N'稕'
													UNION ALL SELECT 'Zhuo',N'籱'
													UNION ALL SELECT 'Zi',N'漬' --漬唨
													UNION ALL SELECT 'Zong',N'縱'
													UNION ALL SELECT 'Zou',N'媰'
													UNION ALL SELECT 'Zu',N'謯'
													UNION ALL SELECT 'Zuan',N'攥'
													UNION ALL SELECT 'Zui',N'欈'
													UNION ALL SELECT 'Zun',N'銌'
													UNION ALL SELECT 'Zuo',N'咗'
                                                        ) t
                                                WHERE   word >= @word COLLATE Chinese_PRC_CS_AS_KS_WS
                                                ORDER BY word ASC
                                               )
                                          ELSE @word
                                     END)
            SET @i = @i + 1
        END
    RETURN @pinyin
END