DBCC DROPCLEANBUFFERS
DBCC FREEPROCCACHE

SET STATISTICS IO ON 

SELECT  *
FROM    dbo.Articles
WHERE   txtContent LIKE '%柳永法%'

SET STATISTICS IO OFF

SET STATISTICS IO ON 
SET STATISTICS TIME ON

SELECT  *
FROM    dbo.Articles
WHERE   dbo.ContainsOne(txtContent, '柳永法') = 1

SET STATISTICS TIME OFF
SET STATISTICS IO OFF